Added tasks to take note ms w/a-Shell; source_error_hanlder

diff --git a/.local/bin/view_video_vlc b/.local/bin/view_video_vlc
--- a/.local/bin/view_video_vlc
+++ b/.local/bin/view_video_vlc
@@ -1,11 +1,11 @@
 #!/bin/sh
 
-source 
-# Open videos with a-shell
+# This script is to open videos with a-shell
+
 clear
 # Show numbered video_dir
 echo "===== VLC ====="
-video_dir="/private/var/mobile/Library/Mobile Documents/com~apple~CloudDocs/Downloads/Videos/vimtips"
+video_dir="/private/var/mobile/Library/Mobile Documents/com~apple~CloudDocs/Downloads/Videos/linux"
 videos=$(ls "$video_dir")
 video_list=$(echo "$videos" | awk '{print NR "\t" $0}')
 count=$(echo "$video_list" | wc -l)
@@ -13,15 +13,15 @@ count=$(echo "$video_list" | wc -l)
 echo "===== VIDEOS LIST ====="
 echo "$video_list"
 
-# Select the number of video
-echo "Enter number from 1 to $count:"
+# Get User selection
+printf "Enter [1..$count]:"
 read num
-selected=$(echo "$video_list" | grep "^$num" ||  echo "[ERROR] Empty value")
-echo "[INFO] This is the chosen video: $selected"
-file=$(echo "$selected" | awk -F '\t' '{print $2}')
+video=$(echo "$video_list" | grep "^$num" ||  echo "[ERROR] Empty value")
+echo "[INFO] You have chosen: $video"
+file=$(echo "$video" | awk -F '\t' '{print $2}')
 # Check if selection is valid
 if [ $num -ge 1 ] && [ $num -le $count ]; then 
 	open "$video_dir/$file" || echo "[ERROR] Not able to view"
 else
-	echo "[ERROR] Invalid!" >&2
+	echo "[ERROR] Select from range [1 - $count]!" >&2
 fi
